import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
  keywords: ["contact", "contact page", "contact us"],
};

export default function ContactPage() {
  return <div className="text-7xl">Contact Page</div>;
}
